### ISSUE TITLE
Need little help migrate issues from Gitlab to Jira Cloud

### ISSUE THREAD

**Issue by taylor-nguyen** [SimeonC/jira-gitlab-seneschal#44]
Hi,

Sorry if this sounds like a dumb question. I am looking into this project to migrate all our Gitlab tickets to Jira cloud. I could see it connects to Jira by Jira credentials. But how does it connect to Gitlab? Do I need to export all issues from Gitlab to Postgres database first? I checked https://bitbucket.org/atlassian/atlassian-connect-express but still not quite sure how things work together. 

Any help is appreciated.

**Comment by SimeonC** [comment]
Hey, the gitlab token is set inside Jira app settings. It’ll prompt you the first time you open the add on in jira and then the token and details are stored (encrypted) in the DB afterwards. Once you’ve logged in you can select which projects you want to migrate and some of the transforms/missing data.

Admittedly I haven’t run the process since we migrated using this so there’s a possibility it may have broken - especially the gitlab markdown - Jira markdown. They keep changing the Jira format...

**Comment by taylor-nguyen** [comment]
Thanks. I tried to run it but got a number of " type "number" does not exist" errors like

`parent: error: type "number" does not exist
      at Parser.parseErrorMessage (/.../jira-gitlab-seneschal/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/.../jira-gitlab-seneschal/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/../jira-gitlab-seneschal/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/../jira-gitlab-seneschal/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)`

Also, how do I host the app on the Internet to connect it to Jira? The part I'm having trouble with is those env variables as I'm not sure what their values should be.

**Comment by SimeonC** [comment]
The ENV vars needed should just be the ones here; https://github.com/SimeonC/jira-gitlab-seneschal/blob/master/config.json#L57-L74 (ignore the `$` sign, ie `$PORT` is `process.env.PORT`)

I have no idea what the error is, never seen it before. What version of postgres are you using?

**Comment by adeweever** [comment]
@taylor-nguyen do you have a fix for that number error? I am getting the same thing.

**Comment by csteiger** [comment]
The number error is in this sql, `CREATE TABLE IF NOT EXISTS "WebhookTransitionMaps" ("jiraProjectId" NUMBER NOT NULL , "jiraProjectKey" VARCHAR(255) NOT NULL, "openStatusIds" VARCHAR(255)[] NOT NULL, "mergeStatusIds" VARCHAR(255)[] NOT NULL, "closeStatusIds" VARCHAR(255)[] NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "clientKey" VARCHAR(255) REFERENCES "WebhookTransitions" ("clientKey") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("jiraProjectId")); `

I manually created this table with jiraProjectId as a varchar and was able to keep going.
