### ISSUE TITLE
Help building and using this project

### ISSUE THREAD

**Issue by fpronto** [SimeonC/jira-gitlab-seneschal#50]
Hi.
Sorry if this is dumb question, but I can't make this project work and don't know why.

I've clone the project into my machine, did the npm run build, after that just run npm start and it simple doesn't work.
I am running the postgres using the command the you provided in the ReadMe.MD

other than the docker command I don't know how to run this program. Can you explain more?

PS: I am getting (I think) an error

```
DatabaseError [SequelizeDatabaseError]: type "number" does not exist
    at Query.formatError (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
From previous event:
    at Query.run (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/query.js:64:23)
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:655:29
From previous event:
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:655:12
From previous event:
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:651:10
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/retry-as-promised/index.js:60:10)
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:641:30
From previous event:
    at Sequelize.query (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:590:23)
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/query-interface.js:236:46
From previous event:
    at QueryInterface.createTable (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/query-interface.js:236:20)
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/model.js:1294:39
From previous event:
    at Function.sync (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/model.js:1294:8)
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:828:50
From previous event:
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:828:22
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Sequelize.sync (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:812:8)
    at /home/fpronto/Projects/jira-gitlab-seneschal/src/server/models/index.js:31:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Client._attachListeners (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:178:9)
    at Client._connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:120:10)
    at Client.connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:152:12)
    at Promise.tap.query (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:158:18)
    at ConnectionManager.connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:121:12)
    at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:50
    at processImmediate (internal/timers.js:461:21) {
  parent: error: type "number" does not exist
      at Parser.parseErrorMessage (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/parser.ts:357:11)
      at Parser.handlePacket (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/parser.ts:186:21)
      at Parser.parse (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/parser.ts:101:30)
      at Socket.<anonymous> (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/index.ts:7:48)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:467:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
  From previous event:
      at Query.run (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/query.js:60:9)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:655:29
  From previous event:
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:655:12
  From previous event:
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:651:10
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/retry-as-promised/index.js:70:21
      at new Promise (<anonymous>)
      at retryAsPromised (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/retry-as-promised/index.js:60:10)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:641:30
  From previous event:
      at Sequelize.query (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:590:23)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/query-interface.js:236:46
  From previous event:
      at QueryInterface.createTable (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/query-interface.js:236:20)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/model.js:1294:39
  From previous event:
      at Function.sync (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/model.js:1294:8)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:828:50
  From previous event:
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:828:22
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Sequelize.sync (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:812:8)
      at /home/fpronto/Projects/jira-gitlab-seneschal/src/server/models/index.js:31:22
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Client._attachListeners (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:178:9)
      at Client._connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:120:10)
      at Client.connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:152:12)
      at Promise.tap.query (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:158:18)
      at ConnectionManager.connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:121:12)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:50
      at processImmediate (internal/timers.js:461:21) {
    length: 93,
    severity: 'ERROR',
    code: '42704',
    detail: undefined,
    hint: undefined,
    position: '69',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_type.c',
    line: '270',
    routine: 'typenameType',
    sql: 'CREATE TABLE IF NOT EXISTS "WebhookTransitionMaps" ("jiraProjectId" NUMBER NOT NULL , "jiraProjectKey" VARCHAR(255) NOT NULL, "openStatusIds" VARCHAR(255)[] NOT NULL, "mergeStatusIds" VARCHAR(255)[] NOT NULL, "closeStatusIds" VARCHAR(255)[] NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "clientKey" VARCHAR(255) REFERENCES "WebhookTransitions" ("clientKey") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("jiraProjectId"));',
    parameters: undefined
  },
  original: error: type "number" does not exist
      at Parser.parseErrorMessage (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/parser.ts:357:11)
      at Parser.handlePacket (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/parser.ts:186:21)
      at Parser.parse (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/parser.ts:101:30)
      at Socket.<anonymous> (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg-protocol/src/index.ts:7:48)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:467:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
  From previous event:
      at Query.run (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/query.js:60:9)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:655:29
  From previous event:
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:655:12
  From previous event:
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:651:10
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/retry-as-promised/index.js:70:21
      at new Promise (<anonymous>)
      at retryAsPromised (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/retry-as-promised/index.js:60:10)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:641:30
  From previous event:
      at Sequelize.query (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:590:23)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/query-interface.js:236:46
  From previous event:
      at QueryInterface.createTable (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/query-interface.js:236:20)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/model.js:1294:39
  From previous event:
      at Function.sync (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/model.js:1294:8)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:828:50
  From previous event:
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:828:22
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Sequelize.sync (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/sequelize.js:812:8)
      at /home/fpronto/Projects/jira-gitlab-seneschal/src/server/models/index.js:31:22
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Client._attachListeners (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:178:9)
      at Client._connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:120:10)
      at Client.connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/pg/lib/client.js:152:12)
      at Promise.tap.query (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:158:18)
      at ConnectionManager.connect (/home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:121:12)
      at /home/fpronto/Projects/jira-gitlab-seneschal/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:50
      at processImmediate (internal/timers.js:461:21) {
    length: 93,
    severity: 'ERROR',
    code: '42704',
    detail: undefined,
    hint: undefined,
    position: '69',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_type.c',
    line: '270',
    routine: 'typenameType',
    sql: 'CREATE TABLE IF NOT EXISTS "WebhookTransitionMaps" ("jiraProjectId" NUMBER NOT NULL , "jiraProjectKey" VARCHAR(255) NOT NULL, "openStatusIds" VARCHAR(255)[] NOT NULL, "mergeStatusIds" VARCHAR(255)[] NOT NULL, "closeStatusIds" VARCHAR(255)[] NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "clientKey" VARCHAR(255) REFERENCES "WebhookTransitions" ("clientKey") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("jiraProjectId"));',
    parameters: undefined
  },
  sql: 'CREATE TABLE IF NOT EXISTS "WebhookTransitionMaps" ("jiraProjectId" NUMBER NOT NULL , "jiraProjectKey" VARCHAR(255) NOT NULL, "openStatusIds" VARCHAR(255)[] NOT NULL, "mergeStatusIds" VARCHAR(255)[] NOT NULL, "closeStatusIds" VARCHAR(255)[] NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "clientKey" VARCHAR(255) REFERENCES "WebhookTransitions" ("clientKey") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("jiraProjectId"));',
  parameters: undefined
}
```

PPS: If I understand the process of running this project I will submit a pull request to improve the ReadMe.MD for the next person that needs this

**Comment by mikekotas** [comment]
Hi @fpronto 

Have you maybe managed to run hsi project and make it work?
In case , could you please share each step required?

Best Regards
Mike

**Comment by fpronto** [comment]
@mikekotas sorry, I just moved away from jira and just using gitlab
